version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./dockerfile/python
    ports:
      - 80:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data_prod:
